"""Public typed API for portable coding-agent inventory declarations."""

from ballen_config.assistants.claude import (
    ClaudePluginInspectionError,
    ClaudeSettingsError,
    ClaudeStableSettings,
    claude_configuration,
    claude_instruction_renderer,
    claude_settings_renderer,
    load_stable_settings,
    plan_claude_plugins,
)
from ballen_config.assistants.claude import (
    install_actions as claude_install_actions,
)
from ballen_config.assistants.codex import (
    CodexPluginInspectionError,
    CodexSettingsError,
    CodexStableSettings,
    codex_configuration,
    codex_instruction_renderer,
    codex_settings_renderer,
    plan_codex_plugins,
)
from ballen_config.assistants.codex import (
    install_actions as codex_install_actions,
)
from ballen_config.assistants.codex import (
    load_stable_settings as load_codex_stable_settings,
)
from ballen_config.assistants.cursor import (
    CursorExtensionInspectionError,
    CursorExtensionPackage,
    ExtensionState,
    cursor_settings_renderer,
    deep_merge,
    jj_graph_action,
    plan_cursor_extension_actions,
    read_bundled_extensions,
    render_settings,
    resolve_extensions,
)
from ballen_config.assistants.cursor import (
    configuration as cursor_configuration,
)
from ballen_config.assistants.cursor import (
    install_actions as cursor_install_actions,
)
from ballen_config.assistants.cursor_plugins import (
    CursorPluginManifest,
    ValidatedCursorLocalPlugin,
    cursor_local_plugin_configuration,
    cursor_marketplace_doctor_checks,
    cursor_marketplace_plan_actions,
    validate_cursor_local_plugin,
    validate_cursor_local_plugins,
)
from ballen_config.assistants.desired_state import (
    AssistantDesiredState,
    AssistantDesiredStateError,
    PluginCatalogProjection,
    load_desired_state,
    project_plugin_catalog,
)
from ballen_config.assistants.hooks import (
    ClaudeHookFragment,
    CursorRegistration,
    claude_hook_fragment,
    cursor_hook_renderer,
    cursor_registration,
    hook_contribution,
    validate_hook_source,
)
from ballen_config.assistants.instructions import render_native_instructions
from ballen_config.assistants.inventory import (
    LoadedCatalog,
    LoadedInventory,
    load_inventory,
    resolve_inventory,
)
from ballen_config.assistants.models import (
    AgentName,
    AssistantInventory,
    CatalogKind,
    CatalogResource,
    ConcreteAgentName,
    ExtensionCatalog,
    ExtensionSpec,
    FileResource,
    HookResource,
    ManualResource,
    Marketplace,
    PluginCatalog,
    PluginSpec,
    PortableResource,
    ResourceBase,
    SkillCatalog,
    SkillRenameSpec,
    SkillSpec,
)
from ballen_config.assistants.orchestrator import AssistantOrchestrator
from ballen_config.assistants.skills import (
    LegacyRenameState,
    RenameTargetClassification,
    SkillCollisionError,
    SkillCopyAction,
    SkillRenameAction,
    SkillRenameBlockedError,
    classify_rename_target,
    declared_skill_name,
    hash_skill_tree,
    managed_tree_spec,
    plan_skill_copies,
    plan_skill_renames,
)

__all__ = [
    "AgentName",
    "AssistantDesiredState",
    "AssistantDesiredStateError",
    "AssistantInventory",
    "AssistantOrchestrator",
    "CatalogKind",
    "CatalogResource",
    "ClaudeHookFragment",
    "ClaudePluginInspectionError",
    "ClaudeSettingsError",
    "ClaudeStableSettings",
    "CodexPluginInspectionError",
    "CodexSettingsError",
    "CodexStableSettings",
    "ConcreteAgentName",
    "CursorExtensionInspectionError",
    "CursorExtensionPackage",
    "CursorPluginManifest",
    "CursorRegistration",
    "ExtensionCatalog",
    "ExtensionSpec",
    "ExtensionState",
    "FileResource",
    "HookResource",
    "LegacyRenameState",
    "LoadedCatalog",
    "LoadedInventory",
    "ManualResource",
    "Marketplace",
    "PluginCatalog",
    "PluginCatalogProjection",
    "PluginSpec",
    "PortableResource",
    "RenameTargetClassification",
    "ResourceBase",
    "SkillCatalog",
    "SkillCollisionError",
    "SkillCopyAction",
    "SkillRenameAction",
    "SkillRenameBlockedError",
    "SkillRenameSpec",
    "SkillSpec",
    "ValidatedCursorLocalPlugin",
    "classify_rename_target",
    "claude_configuration",
    "claude_hook_fragment",
    "claude_install_actions",
    "claude_instruction_renderer",
    "claude_settings_renderer",
    "codex_configuration",
    "codex_install_actions",
    "codex_instruction_renderer",
    "codex_settings_renderer",
    "cursor_configuration",
    "cursor_hook_renderer",
    "cursor_install_actions",
    "cursor_local_plugin_configuration",
    "cursor_marketplace_doctor_checks",
    "cursor_marketplace_plan_actions",
    "cursor_registration",
    "cursor_settings_renderer",
    "declared_skill_name",
    "deep_merge",
    "hash_skill_tree",
    "hook_contribution",
    "jj_graph_action",
    "load_codex_stable_settings",
    "load_desired_state",
    "load_inventory",
    "load_stable_settings",
    "managed_tree_spec",
    "plan_claude_plugins",
    "plan_codex_plugins",
    "plan_cursor_extension_actions",
    "plan_skill_copies",
    "plan_skill_renames",
    "project_plugin_catalog",
    "read_bundled_extensions",
    "render_native_instructions",
    "render_settings",
    "resolve_extensions",
    "resolve_inventory",
    "validate_cursor_local_plugin",
    "validate_cursor_local_plugins",
    "validate_hook_source",
]
